include: package:all_lint_rules_community/all.yaml

analyzer:
  language:
    # strict-casts: true
    # strict-inference: true
    # strict-raw-types: true

  exclude:
    - "test/**"
    - "bricks/**"
    - "bin/cache/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "**/translation_keys.dart"
    - "**/translation_loader.dart"
    - "lib/generated_plugin_registrant.dart"

  errors:
    included_file_warning: ignore

linter:
  rules:
    unnecessary_final: false
    always_specify_types: false
    one_member_abstracts: false
    prefer_double_quotes: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    sort_constructors_first: false
    prefer_final_parameters: false
    prefer_relative_imports: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: false
    diagnostic_describe_all_properties: false
    avoid_classes_with_only_static_members: false
    always_put_required_named_parameters_first: false
